import { Github, Send, Code } from "lucide-react";

export const Footer = () => {
  return (
    <footer className="relative bg-asphalt text-concrete pt-16 pb-8 border-t-4 border-acid z-20">
      <div className="max-w-[100rem] mx-auto px-6 md:px-12">
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 mb-16 border-b border-concrete/10 pb-12">
          <div>
            <h2 className="font-display text-5xl md:text-7xl uppercase tracking-tighter mb-4">
              Whiezel<span className="text-acid">.</span>
            </h2>
            <p className="font-mono text-sm max-w-md opacity-60">
              Brutalist aesthetics meets functional typescript code.
              (not very functional anymore :c).
            </p>
          </div>

          <div className="flex flex-col justify-end items-start md:items-end text-left md:text-right">
             <div className="bg-concrete/10 p-4 border border-concrete/20 mb-4 backdrop-blur-sm">
                <p className="font-bold text-acid font-mono text-xs mb-1">/// SYSTEM STATUS: DEMO MODE</p>
                <p className="font-mono text-xs leading-relaxed max-w-sm">
                  This is not a real commercial project. 
                  Created for <u>Resume/Portfolio</u> purposes.
                  <br />
                  <span className="opacity-70 mt-1 inline-block">
                    * All product images generated by AI using <b>Nano Banana Pro</b>.
                  </span>
                </p>
             </div>
             <a 
               href="https://github.com/whitfielfur/whiezel-drop" 
               target="_blank"
               rel="noreferrer"
               className="inline-flex items-center gap-2 font-mono text-xs hover:text-acid transition-colors underline decoration-1 underline-offset-4"
             >
               VIEW SOURCE CODE <Code size={12} />
             </a>
          </div>
        </div>

        <div className="flex flex-col md:flex-row justify-between items-center gap-6 font-mono text-xs text-concrete/40 uppercase">
          
          <div className="flex gap-8">
            <span>2026 Whitfiel</span>
          </div>

          <div className="flex gap-6">
            <a 
              href="https://github.com/whitfielfur" 
              target="_blank" 
              rel="noreferrer" 
              className="hover:text-white transition-colors flex items-center gap-2"
            >
              <Github size={14} /> GitHub
            </a>
            
            <a 
              href="https://t.me/holyresume" 
              target="_blank" 
              rel="noreferrer" 
              className="hover:text-white transition-colors flex items-center gap-2"
            >
              <Send size={14} /> Telegram
            </a>
            
            <span className="text-acid">::</span>
            <span>Berlin / Tokyo / Web</span>
          </div>
          
        </div>
      </div>

      <div className="absolute bottom-0 left-0 w-full h-1 bg-gradient-to-r from-asphalt via-acid to-asphalt opacity-50" />
    </footer>
  );
};